### ISSUE TITLE
workflow 中引用 index.php 路径名称大小写不一致

### ISSUE THREAD

**Issue by oe** [larry-666/Dou-figure-alfred-workflow#6]
我的机器磁盘是 case sensitive 的. 看到php源文件名称为 `Index.php`(首字母大写), 但是 workflow 中引用的路径多处为 `index.php`, 导致了在我电脑上该workflow不可用. 目前我已自行修正.

另外一个问题: 输入搜索关键字后必须按回车才能搜索, 略有些不方便.

**Comment by KilluaaaCHEN** [comment]
已修复大小写问题,操作流程已优化,感谢建议

**Comment by oe** [comment]
刚下载安装了最新版, 由于之前已安装了旧版, 安装新版后, 新版覆盖了旧版 , 新版无法使用. 删掉重装功能正常.

另外有两个建议:
1. workflow 包不应包含 preview.gif,  本来几十K的包, 变成了近3M.  包里面有两个 cache文件, 应该也是不需要打进来的吧
![image](https://user-images.githubusercontent.com/1655294/38659605-d724fd86-3e5c-11e8-9d65-9a564b54aeeb.png)
2. 用户按回车后, 可以把图片下载到系统的临时文件夹 `$TMPDIR`, 并自动复制到系统剪贴板, 同时弹出系统 notifcation 通知用户已复制. 
3. 搜索的优化: 
    1. 快速输入 `666`, 可以发先结果列表切换了两次, 体验不太好, 即搜索了两次, 做适当的延时(debounce), 等输入完再搜索, 停顿超过 200ms 再发起搜索
    2. 慢速输入 `666`,  由于表情接口调用需要耗时较长, 也就会看到 输入完 `66` 看到的是 `6` 的结果, 输入完 `666` 看到的是 `66` 的结果, 再稍等一会才显示  `666` 的结果. 让人感觉有些焦虑. 是否可以在用户输入新内容时, 列表顶部提示 `正在搜索xxx`
    3. 如上, 慢速输入 `666`, 会搜索三次, 若删除末尾的一个 `6`,  可以观察到又稍等片刻才更新列表, 即又重复搜索了一次. 可在一次使用时, 缓存搜索结果, 若匹配到已搜索的关键字, 直接使用缓存结果即可

**Comment by KilluaaaCHEN** [comment]
1. 已重新打包
2. Alfred好像做不到复制文件功能
3. 原来操作就是按一下Enter解决搜索延迟的问题的,两种方式看个人喜好吧

**Comment by oe** [comment]
问题2 我也搜索了下, 貌似可以借助`osascript`实现复制图片, 看起来有些复杂  
问题3 是我有点抬杠了

THANK YOU
